name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install OctoVersion
      run: |
        dotnet new tool-manifest
        dotnet tool install OctoVersion.Tool
     
    - name: Calculate Version
      id: calculate_version
      shell: bash
      run: |
        dotnet tool run octoversion --CurrentBranch=${{ github.head_ref || github.ref }} --Patch ${{ github.run_number }} --DetectEnvironment true
        echo $OCTOVERSION_FullSemVer

    - name: 🔐 Inject secrets
      run: |
        perl -pi -e 's/\$\{\{ secrets.WLAN_SSID \}\}/$ENV{WLAN_SSID}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.WLAN_PASSWD \}\}/$ENV{WLAN_PASSWD}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.SEQ_URL \}\}/$ENV{SEQ_URL}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.SEQ_API_KEY \}\}/$ENV{SEQ_API_KEY}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.IO_USERNAME \}\}/$ENV{IO_USERNAME}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.IO_KEY \}\}/$ENV{IO_KEY}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.IO_FEEDNAME \}\}/$ENV{IO_FEEDNAME}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.OTA_ENDPOINT \}\}/$ENV{OTA_ENDPOINT}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.OTA_USERNAME \}\}/$ENV{OTA_USERNAME}/' sketch/config.h
        perl -pi -e 's/\$\{\{ secrets.OTA_PASSWORD \}\}/$ENV{OTA_PASSWORD}/' sketch/config.h
        perl -pi -e 's/\$\{\{ github.VERSION_NUMBER \}\}/$ENV{VERSION_NUMBER}/' sketch/config.h
      env:
        WLAN_SSID: ${{ secrets.WLAN_SSID }}
        WLAN_PASSWD: ${{ secrets.WLAN_PASSWD }}
        SEQ_URL: ${{ secrets.SEQ_URL }}
        SEQ_API_KEY: ${{ secrets.SEQ_API_KEY }}
        IO_USERNAME: ${{ secrets.IO_USERNAME }}
        IO_KEY: ${{ secrets.IO_KEY }}
        IO_FEEDNAME: ${{ secrets.IO_FEEDNAME }}
        OTA_ENDPOINT: ${{ secrets.OTA_ENDPOINT }}
        OTA_USERNAME: ${{ secrets.OTA_USERNAME }}
        OTA_PASSWORD: ${{ secrets.OTA_PASSWORD }}
        VERSION_NUMBER: ${{ steps.calculate_version.outputs.octoversion_fullsemver }}

    # cant get this to work via the required-libraries
    - name: Get HCSR04 library 
      uses: actions/checkout@v2
      with:
        repository: gamegine/HCSR04-ultrasonic-sensor-lib
        ref: master
        path: CustomHCSR04 # must contain string "Custom"

    - name: Get ezTime library 
      uses: actions/checkout@v2
      with:
        repository: ropg/ezTime
        ref: master
        path: CustomEzTime # must contain string "Custom"

    - name: Compile 
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp8266:esp8266:nodemcuv2:eesz=4M3M,xtal=80
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json

    - name: 🗜 Zip binaries 
      run: |
        zip -r --junk-paths water-tank-sensor.${{ steps.calculate_version.outputs.octoversion_fullsemver }}.zip ./sketch/build/esp8266.esp8266.nodemcuv2

    - name: 🐙 Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
      with:
        version: latest
      
    - name: 🐙 Push a package to Octopus Deploy
      uses: OctopusDeploy/push-package-action@v1.1.1
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        packages: water-tank-sensor.${{ steps.calculate_version.outputs.octoversion_fullsemver }}.zip
        server: ${{ secrets.OCTOPUS_SERVER }}

    - name: 🐙 Create a release in Octopus Deploy
      uses: OctopusDeploy/create-release-action@v2
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        project: 'Water Tank Sensor'
        server: ${{ secrets.OCTOPUS_SERVER }}
        release_number: ${{ steps.calculate_version.outputs.octoversion_fullsemver }}
        packages: water-tank-sensor:${{ steps.calculate_version.outputs.octoversion_fullsemver }}
