name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Test compiling examples for esp8266
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - run: |
        perl -pi -e 's/\$\{\{ secrets.WLAN_SSID \}\}/"$ENV{WLAN_SSID}"/' sketch/sketch.ino
        perl -pi -e 's/\$\{\{ secrets.WLAN_PASSWD \}\}/"$ENV{WLAN_PASSWD}"/' sketch/sketch.ino
        perl -pi -e 's/\$\{\{ secrets.IO_USERNAME \}\}/"$ENV{IO_USERNAME}"/' sketch/sketch.ino
        perl -pi -e 's/\$\{\{ secrets.IO_KEY \}\}/"$ENV{IO_KEY}"/' sketch/sketch.ino
        perl -pi -e 's/\$\{\{ secrets.IO_FEEDNAME \}\}/"$ENV{IO_FEEDNAME}"/' sketch/sketch.ino
      env:
        WLAN_SSID: ${{ secrets.WLAN_SSID }}
        WLAN_PASSWD: ${{ secrets.WLAN_PASSWD }}
        IO_USERNAME: ${{ secrets.IO_USERNAME }}
        IO_KEY: ${{ secrets.IO_KEY }}
        IO_FEEDNAME: ${{ secrets.IO_FEEDNAME }}

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp8266:esp8266:nodemcuv2:eesz=4M3M,xtal=80
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        required-libraries: HCSR04_ultrasonic_sensor
